name = "Flatten"
uuid = "4c728ea3-d9ee-5c9a-9642-b6f7d7dc04fa"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>"]
version = "0.1.0"

[extras]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Parameters", "Test"]
